"""
Response schema(s) for the agent endpoints.

Stage 4 keeps this deliberately thin: just enough to describe what
POST /api/agent/init returns. Persona fields (name/description as
generated by the LLM) get richer starting Stage 5/8 — this schema will
grow with them rather than being redefined.
"""
from datetime import datetime

from pydantic import BaseModel, ConfigDict


class AgentInitResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    agentId: str
    status: str
    personaName: str
    createdAt: datetime
